[package]
name = "dragon_skeleton"
authors = ["Kevin Fischer <kfischer_okarin@yahoo.co.jp>"]
version = "2023.01.24.2"
homepage = "https://github.com/kfischer-okarin/dragon_skeleton"
keywords = []

# Optional:
# documentation = "https://example.com"
# repository = "http://github.com/example/example"

# Which files do you want to be automatically required from your package.
requires = [
  "lib/dragon_skeleton/animations.rb",
  "lib/dragon_skeleton/buttons.rb",
  "lib/dragon_skeleton/file_formats/aseprite_json.rb",
  "lib/dragon_skeleton/long_calculation.rb",
  "lib/dragon_skeleton/long_calculation/long_calculation_fiber.rb",
  "lib/dragon_skeleton/pathfinding.rb",
  "lib/dragon_skeleton/pathfinding/a_star.rb",
  "lib/dragon_skeleton/pathfinding/priority_queue.rb",
  "lib/dragon_skeleton/screen.rb"
]


[package.installs]

[dragonruby]
version = "3"
edition = "standard"
